name: urlwatch

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: 'Asia/Hong_Kong'
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -U "lxml<5"
          pip install pyyaml minidb requests keyring appdirs cssselect html2text urlwatch
      - name: Download cached db
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: main.yml
          workflow_conclusion: completed
          branch: master
          name: cachedb
      - name: Set secret
        run: |
          sed -i "s/gmail_app_password/${{ secrets.GMAIL_APP_PASSWORD }}/" urlwatch.yaml
      - name: Run urlwatch
        run: |
          urlwatch --config=urlwatch.yaml --urls=urls.yaml --cache=cache.db
      - name: Upload updated db
        uses: actions/upload-artifact@v4
        with:
          name: cachedb
          path: cache.db
          retention-days: 1
